/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GoLiveRouteImport } from './routes/go-live'
import { Route as MyStudioRouteImport } from './routes/my-studio'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMatDashboardRouteImport } from './routes/admin.mat-dashboard'
import { Route as AdminMatOrdersRouteImport } from './routes/admin.mat-orders'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as ExploreCategoryRouteImport } from './routes/explore.$category'
import { Route as MatAboutRouteImport } from './routes/mat.about'
import { Route as MatExploreRouteImport } from './routes/mat.explore'
import { Route as MatOrderRouteImport } from './routes/mat.order'
import { Route as MatPracticeRouteImport } from './routes/mat.practice'
import { Route as PracticeVideoIdRouteImport } from './routes/practice.$videoId'
import { Route as SigninIndexRouteImport } from './routes/signin.index'
import { Route as SigninExplorerRouteImport } from './routes/signin.explorer'
import { Route as SigninPractitionerRouteImport } from './routes/signin.practitioner'
import { Route as AdminVideosIndexRouteImport } from './routes/admin.videos.index'
import { Route as AdminVideosNewRouteImport } from './routes/admin.videos.new'
import { Route as MatBuyIndexRouteImport } from './routes/mat.buy.index'
import { Route as MatBuyDeliveryAddressRouteImport } from './routes/mat.buy.delivery-address'
import { Route as MatBuyMatMeasurementsRouteImport } from './routes/mat.buy.mat-measurements'
import { Route as MatBuyMatPaymentRouteImport } from './routes/mat.buy.mat-payment'
import { Route as MatBuyOrderConfirmationRouteImport } from './routes/mat.buy.order-confirmation'
import { Route as MatCheckoutSuccessRouteImport } from './routes/mat.checkout.success'
import { Route as MatExploreCategoryRouteImport } from './routes/mat.explore.$category'
import { Route as MatPracticeVideoIdRouteImport } from './routes/mat.practice.$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveRoute = GoLiveRouteImport.update({
  id: '/go-live',
  path: '/go-live',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStudioRoute = MyStudioRouteImport.update({
  id: '/my-studio',
  path: '/my-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatDashboardRoute = AdminMatDashboardRouteImport.update({
  id: '/mat-dashboard',
  path: '/mat-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatOrdersRoute = AdminMatOrdersRouteImport.update({
  id: '/mat-orders',
  path: '/mat-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const ExploreCategoryRoute = ExploreCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ExploreRoute,
} as any)
const MatAboutRoute = MatAboutRouteImport.update({
  id: '/mat/about',
  path: '/mat/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MatExploreRoute = MatExploreRouteImport.update({
  id: '/mat/explore',
  path: '/mat/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MatOrderRoute = MatOrderRouteImport.update({
  id: '/mat/order',
  path: '/mat/order',
  getParentRoute: () => rootRouteImport,
} as any)
const MatPracticeRoute = MatPracticeRouteImport.update({
  id: '/mat/practice',
  path: '/mat/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeVideoIdRoute = PracticeVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => PracticeRoute,
} as any)
const SigninIndexRoute = SigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninExplorerRoute = SigninExplorerRouteImport.update({
  id: '/signin/explorer',
  path: '/signin/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninPractitionerRoute = SigninPractitionerRouteImport.update({
  id: '/signin/practitioner',
  path: '/signin/practitioner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosIndexRoute = AdminVideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminVideosRoute,
} as any)
const AdminVideosNewRoute = AdminVideosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminVideosRoute,
} as any)
const MatBuyIndexRoute = MatBuyIndexRouteImport.update({
  id: '/mat/buy/',
  path: '/mat/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatBuyDeliveryAddressRoute = MatBuyDeliveryAddressRouteImport.update({
  id: '/mat/buy/delivery-address',
  path: '/mat/buy/delivery-address',
  getParentRoute: () => rootRouteImport,
} as any)
const MatBuyMatMeasurementsRoute = MatBuyMatMeasurementsRouteImport.update({
  id: '/mat/buy/mat-measurements',
  path: '/mat/buy/mat-measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const MatBuyMatPaymentRoute = MatBuyMatPaymentRouteImport.update({
  id: '/mat/buy/mat-payment',
  path: '/mat/buy/mat-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MatBuyOrderConfirmationRoute = MatBuyOrderConfirmationRouteImport.update({
  id: '/mat/buy/order-confirmation',
  path: '/mat/buy/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const MatCheckoutSuccessRoute = MatCheckoutSuccessRouteImport.update({
  id: '/mat/checkout/success',
  path: '/mat/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const MatExploreCategoryRoute = MatExploreCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => MatExploreRoute,
} as any)
const MatPracticeVideoIdRoute = MatPracticeVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => MatPracticeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/go-live': typeof GoLiveRoute
  '/my-studio': typeof MyStudioRoute
  '/practice': typeof PracticeRouteWithChildren
  '/admin/mat-dashboard': typeof AdminMatDashboardRoute
  '/admin/mat-orders': typeof AdminMatOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/explore/$category': typeof ExploreCategoryRoute
  '/mat/about': typeof MatAboutRoute
  '/mat/explore': typeof MatExploreRouteWithChildren
  '/mat/order': typeof MatOrderRoute
  '/mat/practice': typeof MatPracticeRouteWithChildren
  '/practice/$videoId': typeof PracticeVideoIdRoute
  '/signin/explorer': typeof SigninExplorerRoute
  '/signin/practitioner': typeof SigninPractitionerRoute
  '/admin/': typeof AdminIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/mat/buy/delivery-address': typeof MatBuyDeliveryAddressRoute
  '/mat/buy/mat-measurements': typeof MatBuyMatMeasurementsRoute
  '/mat/buy/mat-payment': typeof MatBuyMatPaymentRoute
  '/mat/buy/order-confirmation': typeof MatBuyOrderConfirmationRoute
  '/mat/checkout/success': typeof MatCheckoutSuccessRoute
  '/mat/explore/$category': typeof MatExploreCategoryRoute
  '/mat/practice/$videoId': typeof MatPracticeVideoIdRoute
  '/admin/videos/': typeof AdminVideosIndexRoute
  '/mat/buy/': typeof MatBuyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/go-live': typeof GoLiveRoute
  '/my-studio': typeof MyStudioRoute
  '/practice': typeof PracticeRouteWithChildren
  '/admin/mat-dashboard': typeof AdminMatDashboardRoute
  '/admin/mat-orders': typeof AdminMatOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/mat/about': typeof MatAboutRoute
  '/mat/explore': typeof MatExploreRouteWithChildren
  '/mat/order': typeof MatOrderRoute
  '/mat/practice': typeof MatPracticeRouteWithChildren
  '/practice/$videoId': typeof PracticeVideoIdRoute
  '/signin/explorer': typeof SigninExplorerRoute
  '/signin/practitioner': typeof SigninPractitionerRoute
  '/admin': typeof AdminIndexRoute
  '/signin': typeof SigninIndexRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/mat/buy/delivery-address': typeof MatBuyDeliveryAddressRoute
  '/mat/buy/mat-measurements': typeof MatBuyMatMeasurementsRoute
  '/mat/buy/mat-payment': typeof MatBuyMatPaymentRoute
  '/mat/buy/order-confirmation': typeof MatBuyOrderConfirmationRoute
  '/mat/checkout/success': typeof MatCheckoutSuccessRoute
  '/mat/explore/$category': typeof MatExploreCategoryRoute
  '/mat/practice/$videoId': typeof MatPracticeVideoIdRoute
  '/admin/videos': typeof AdminVideosIndexRoute
  '/mat/buy': typeof MatBuyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/go-live': typeof GoLiveRoute
  '/my-studio': typeof MyStudioRoute
  '/practice': typeof PracticeRouteWithChildren
  '/admin/mat-dashboard': typeof AdminMatDashboardRoute
  '/admin/mat-orders': typeof AdminMatOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRouteWithChildren
  '/explore/$category': typeof ExploreCategoryRoute
  '/mat/about': typeof MatAboutRoute
  '/mat/explore': typeof MatExploreRouteWithChildren
  '/mat/order': typeof MatOrderRoute
  '/mat/practice': typeof MatPracticeRouteWithChildren
  '/practice/$videoId': typeof PracticeVideoIdRoute
  '/signin/explorer': typeof SigninExplorerRoute
  '/signin/practitioner': typeof SigninPractitionerRoute
  '/admin/': typeof AdminIndexRoute
  '/signin/': typeof SigninIndexRoute
  '/admin/videos/new': typeof AdminVideosNewRoute
  '/mat/buy/delivery-address': typeof MatBuyDeliveryAddressRoute
  '/mat/buy/mat-measurements': typeof MatBuyMatMeasurementsRoute
  '/mat/buy/mat-payment': typeof MatBuyMatPaymentRoute
  '/mat/buy/order-confirmation': typeof MatBuyOrderConfirmationRoute
  '/mat/checkout/success': typeof MatCheckoutSuccessRoute
  '/mat/explore/$category': typeof MatExploreCategoryRoute
  '/mat/practice/$videoId': typeof MatPracticeVideoIdRoute
  '/admin/videos/': typeof AdminVideosIndexRoute
  '/mat/buy/': typeof MatBuyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/explore'
    | '/go-live'
    | '/my-studio'
    | '/practice'
    | '/admin/mat-dashboard'
    | '/admin/mat-orders'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/videos'
    | '/explore/$category'
    | '/mat/about'
    | '/mat/explore'
    | '/mat/order'
    | '/mat/practice'
    | '/practice/$videoId'
    | '/signin/explorer'
    | '/signin/practitioner'
    | '/admin/'
    | '/signin/'
    | '/admin/videos/new'
    | '/mat/buy/delivery-address'
    | '/mat/buy/mat-measurements'
    | '/mat/buy/mat-payment'
    | '/mat/buy/order-confirmation'
    | '/mat/checkout/success'
    | '/mat/explore/$category'
    | '/mat/practice/$videoId'
    | '/admin/videos/'
    | '/mat/buy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/go-live'
    | '/my-studio'
    | '/practice'
    | '/admin/mat-dashboard'
    | '/admin/mat-orders'
    | '/admin/settings'
    | '/admin/users'
    | '/explore/$category'
    | '/mat/about'
    | '/mat/explore'
    | '/mat/order'
    | '/mat/practice'
    | '/practice/$videoId'
    | '/signin/explorer'
    | '/signin/practitioner'
    | '/admin'
    | '/signin'
    | '/admin/videos/new'
    | '/mat/buy/delivery-address'
    | '/mat/buy/mat-measurements'
    | '/mat/buy/mat-payment'
    | '/mat/buy/order-confirmation'
    | '/mat/checkout/success'
    | '/mat/explore/$category'
    | '/mat/practice/$videoId'
    | '/admin/videos'
    | '/mat/buy'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/explore'
    | '/go-live'
    | '/my-studio'
    | '/practice'
    | '/admin/mat-dashboard'
    | '/admin/mat-orders'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/videos'
    | '/explore/$category'
    | '/mat/about'
    | '/mat/explore'
    | '/mat/order'
    | '/mat/practice'
    | '/practice/$videoId'
    | '/signin/explorer'
    | '/signin/practitioner'
    | '/admin/'
    | '/signin/'
    | '/admin/videos/new'
    | '/mat/buy/delivery-address'
    | '/mat/buy/mat-measurements'
    | '/mat/buy/mat-payment'
    | '/mat/buy/order-confirmation'
    | '/mat/checkout/success'
    | '/mat/explore/$category'
    | '/mat/practice/$videoId'
    | '/admin/videos/'
    | '/mat/buy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ExploreRoute: typeof ExploreRouteWithChildren
  GoLiveRoute: typeof GoLiveRoute
  MyStudioRoute: typeof MyStudioRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  MatAboutRoute: typeof MatAboutRoute
  MatExploreRoute: typeof MatExploreRouteWithChildren
  MatOrderRoute: typeof MatOrderRoute
  MatPracticeRoute: typeof MatPracticeRouteWithChildren
  SigninExplorerRoute: typeof SigninExplorerRoute
  SigninPractitionerRoute: typeof SigninPractitionerRoute
  SigninIndexRoute: typeof SigninIndexRoute
  MatBuyDeliveryAddressRoute: typeof MatBuyDeliveryAddressRoute
  MatBuyMatMeasurementsRoute: typeof MatBuyMatMeasurementsRoute
  MatBuyMatPaymentRoute: typeof MatBuyMatPaymentRoute
  MatBuyOrderConfirmationRoute: typeof MatBuyOrderConfirmationRoute
  MatCheckoutSuccessRoute: typeof MatCheckoutSuccessRoute
  MatBuyIndexRoute: typeof MatBuyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live': {
      id: '/go-live'
      path: '/go-live'
      fullPath: '/go-live'
      preLoaderRoute: typeof GoLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-studio': {
      id: '/my-studio'
      path: '/my-studio'
      fullPath: '/my-studio'
      preLoaderRoute: typeof MyStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mat-dashboard': {
      id: '/admin/mat-dashboard'
      path: '/mat-dashboard'
      fullPath: '/admin/mat-dashboard'
      preLoaderRoute: typeof AdminMatDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mat-orders': {
      id: '/admin/mat-orders'
      path: '/mat-orders'
      fullPath: '/admin/mat-orders'
      preLoaderRoute: typeof AdminMatOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/explore/$category': {
      id: '/explore/$category'
      path: '/$category'
      fullPath: '/explore/$category'
      preLoaderRoute: typeof ExploreCategoryRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/mat/about': {
      id: '/mat/about'
      path: '/mat/about'
      fullPath: '/mat/about'
      preLoaderRoute: typeof MatAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat/explore': {
      id: '/mat/explore'
      path: '/mat/explore'
      fullPath: '/mat/explore'
      preLoaderRoute: typeof MatExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat/order': {
      id: '/mat/order'
      path: '/mat/order'
      fullPath: '/mat/order'
      preLoaderRoute: typeof MatOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat/practice': {
      id: '/mat/practice'
      path: '/mat/practice'
      fullPath: '/mat/practice'
      preLoaderRoute: typeof MatPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$videoId': {
      id: '/practice/$videoId'
      path: '/$videoId'
      fullPath: '/practice/$videoId'
      preLoaderRoute: typeof PracticeVideoIdRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof SigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/explorer': {
      id: '/signin/explorer'
      path: '/signin/explorer'
      fullPath: '/signin/explorer'
      preLoaderRoute: typeof SigninExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/practitioner': {
      id: '/signin/practitioner'
      path: '/signin/practitioner'
      fullPath: '/signin/practitioner'
      preLoaderRoute: typeof SigninPractitionerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos/': {
      id: '/admin/videos/'
      path: '/'
      fullPath: '/admin/videos/'
      preLoaderRoute: typeof AdminVideosIndexRouteImport
      parentRoute: typeof AdminVideosRoute
    }
    '/admin/videos/new': {
      id: '/admin/videos/new'
      path: '/new'
      fullPath: '/admin/videos/new'
      preLoaderRoute: typeof AdminVideosNewRouteImport
      parentRoute: typeof AdminVideosRoute
    }
    '/mat/buy/': {
      id: '/mat/buy/'
      path: '/mat/buy'
      fullPath: '/mat/buy/'
      preLoaderRoute: typeof MatBuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat/buy/delivery-address': {
      id: '/mat/buy/delivery-address'
      path: '/mat/buy/delivery-address'
      fullPath: '/mat/buy/delivery-address'
      preLoaderRoute: typeof MatBuyDeliveryAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat/buy/mat-measurements': {
      id: '/mat/buy/mat-measurements'
      path: '/mat/buy/mat-measurements'
      fullPath: '/mat/buy/mat-measurements'
      preLoaderRoute: typeof MatBuyMatMeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat/buy/mat-payment': {
      id: '/mat/buy/mat-payment'
      path: '/mat/buy/mat-payment'
      fullPath: '/mat/buy/mat-payment'
      preLoaderRoute: typeof MatBuyMatPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat/buy/order-confirmation': {
      id: '/mat/buy/order-confirmation'
      path: '/mat/buy/order-confirmation'
      fullPath: '/mat/buy/order-confirmation'
      preLoaderRoute: typeof MatBuyOrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat/checkout/success': {
      id: '/mat/checkout/success'
      path: '/mat/checkout/success'
      fullPath: '/mat/checkout/success'
      preLoaderRoute: typeof MatCheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mat/explore/$category': {
      id: '/mat/explore/$category'
      path: '/$category'
      fullPath: '/mat/explore/$category'
      preLoaderRoute: typeof MatExploreCategoryRouteImport
      parentRoute: typeof MatExploreRoute
    }
    '/mat/practice/$videoId': {
      id: '/mat/practice/$videoId'
      path: '/$videoId'
      fullPath: '/mat/practice/$videoId'
      preLoaderRoute: typeof MatPracticeVideoIdRouteImport
      parentRoute: typeof MatPracticeRoute
    }
  }
}

interface AdminVideosRouteChildren {
  AdminVideosNewRoute: typeof AdminVideosNewRoute
  AdminVideosIndexRoute: typeof AdminVideosIndexRoute
}

const AdminVideosRouteChildren: AdminVideosRouteChildren = {
  AdminVideosNewRoute: AdminVideosNewRoute,
  AdminVideosIndexRoute: AdminVideosIndexRoute,
}

const AdminVideosRouteWithChildren = AdminVideosRoute._addFileChildren(
  AdminVideosRouteChildren,
)

interface AdminRouteChildren {
  AdminMatDashboardRoute: typeof AdminMatDashboardRoute
  AdminMatOrdersRoute: typeof AdminMatOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMatDashboardRoute: AdminMatDashboardRoute,
  AdminMatOrdersRoute: AdminMatOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExploreRouteChildren {
  ExploreCategoryRoute: typeof ExploreCategoryRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreCategoryRoute: ExploreCategoryRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface PracticeRouteChildren {
  PracticeVideoIdRoute: typeof PracticeVideoIdRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeVideoIdRoute: PracticeVideoIdRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

interface MatExploreRouteChildren {
  MatExploreCategoryRoute: typeof MatExploreCategoryRoute
}

const MatExploreRouteChildren: MatExploreRouteChildren = {
  MatExploreCategoryRoute: MatExploreCategoryRoute,
}

const MatExploreRouteWithChildren = MatExploreRoute._addFileChildren(
  MatExploreRouteChildren,
)

interface MatPracticeRouteChildren {
  MatPracticeVideoIdRoute: typeof MatPracticeVideoIdRoute
}

const MatPracticeRouteChildren: MatPracticeRouteChildren = {
  MatPracticeVideoIdRoute: MatPracticeVideoIdRoute,
}

const MatPracticeRouteWithChildren = MatPracticeRoute._addFileChildren(
  MatPracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ExploreRoute: ExploreRouteWithChildren,
  GoLiveRoute: GoLiveRoute,
  MyStudioRoute: MyStudioRoute,
  PracticeRoute: PracticeRouteWithChildren,
  MatAboutRoute: MatAboutRoute,
  MatExploreRoute: MatExploreRouteWithChildren,
  MatOrderRoute: MatOrderRoute,
  MatPracticeRoute: MatPracticeRouteWithChildren,
  SigninExplorerRoute: SigninExplorerRoute,
  SigninPractitionerRoute: SigninPractitionerRoute,
  SigninIndexRoute: SigninIndexRoute,
  MatBuyDeliveryAddressRoute: MatBuyDeliveryAddressRoute,
  MatBuyMatMeasurementsRoute: MatBuyMatMeasurementsRoute,
  MatBuyMatPaymentRoute: MatBuyMatPaymentRoute,
  MatBuyOrderConfirmationRoute: MatBuyOrderConfirmationRoute,
  MatCheckoutSuccessRoute: MatCheckoutSuccessRoute,
  MatBuyIndexRoute: MatBuyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
